#%RAML 1.0
title: API of PIServer
description: PIServer will be use to control all hardware in home
version: v1
baseUri: http://piserver.local/api/v1
mediaType: application/json

# Declaration of types
types: 
  specific:
    description: Specific information about device
    type: object
    properties: 
      id:
        description: ID of this device
        type: string
        required: true
      state:
        description: Current state of port
        type: boolean
        required: true
      topic:
        description: Current topic to publish
        enum: [ switch, together ]
        required: true
  info:
    description: General information about device
    type: object
    properties: 
      location:
        description: Location where this device is
        type: string
        required: true
        example: bedroom
      name:
        description: Name given for this port, this will be sync in all devices connected do PIServer
        type: string
        required: true
        example: light
      together:
        description: If type of port is joint, other ports will be turn off before that is turn on
        required: false
        type: array
        items: 
          description: ID of port that is work together with this port
          type: string
          required: true
  device:
    description: All informtation about device
    type: [ info, specific ]
  pagination:
    description: Information about pagination
    type: object
    properties: 
      page: 
        description: Current page to return
        type: number
        required: true
        minimum: 0
        format: int32
        multipleOf: 1
      size:
        description: Size of page, how many items each request will return
        type: number
        required: true
        minimum: 1
        format: int32
        multipleOf: 1

# Declaration of Traits
traits: 
  queryPagination:
    queryParameters: 
      pagination:
        required: false
        type: pagination

# Declararion of Routes
/device:
  /list:
    get:
      description: List all devices that server know
      is: [ queryPagination ]
      responses: 
        200:
          body: 
            application/json:
              type: device[]
              minItems: 1
  /{id}:
    uriParameters: 
      id: 
        description: ID of device
        type: string
        required: true
    get:
      description: Get only a device with this ID
      responses: 
        200:
          body: 
            application/json:
              type: device
    patch:
      body:
        application/json:
          description: Information to change in device
          type: info
        
